### ISSUE TITLE
Plygon is not connected as a contour

### ISSUE THREAD

**Issue by MingxuanGu** [ChristianMarzahl/Exact#73]
I'm now using polygon to annotate for segmentation map, but I find sometimes the start point and the end point of the polygons are not connected.
![b390c6da68f8410d05705ce4a701381](https://user-images.githubusercontent.com/34170154/142003819-e6fca964-7b58-4457-b982-5cfadd303d8f.png)
![446726e9db04711d28ffb06e75ead48](https://user-images.githubusercontent.com/34170154/142003848-9383932d-5eab-40b8-9ce0-cf95a6bd2e2e.png)
The first image shows my annotation on the Exact server. The second image shows the annotation that I downloaded from the server.
This error can be reproduced when the starting point and end point of the polygon are too far away from each other.

**Comment by ChristianMarzahl** [comment]
Dear StormyaP,

is "closed" set in your settings?
![image](https://user-images.githubusercontent.com/22664224/142010070-d036438a-0e9e-4c2d-a3bc-70dfd2722286.png)

**Comment by StormyaP** [comment]
Hi Christian,

 

Yes it’s in my setting.

 

Best,

Mingxuan

**Comment by ChristianMarzahl** [comment]
@OettlM do you have an idea? 

With kind regards,
Christian

**Comment by OettlM** [comment]
@MingxuanGu can you share the way the second image is created? How to you convert the polygon vector to pixel wise segmentations?

**Comment by OettlM** [comment]
Okay, I think I see where the issue is here.
The data you get is a vector containing each point that is part of the polygon annotation.

What you do in your code is to assign each pixel the value of the point it contains. However, the annotations in EXACT are polygons, so you dont nessesarly have a point for every pixel of the contour, since it just connects each point to the next.

A solution to this behaviour would be to use a function that interprets the vector as a polygon and draws it into your image.
OpenCV offers functionality to easily do that. https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html

![image](https://user-images.githubusercontent.com/82029523/142198029-877d5af5-f659-473f-b8ad-82730c744041.png)

Here is an example how you can use cv2.drawContours to draw the polygons. You can ignore the middle part where I sort the annotations, depending on the area size, which is only relevant if you have overlapping annotations.

In this case the function is also parameterized to directly draw filled polygons, so you dont have to do that yourself afterwards.

**Comment by MingxuanGu** [comment]
Amazing, it works! Thanks!

**Comment by ChristianMarzahl** [comment]
Big thanks to @OettlM
